### ISSUE TITLE
换成browserHistory，路由不起作用了呢

### ISSUE THREAD

**Issue by linginging** [sorrycc/blog#11]
// 1. Initialize
const app = dva({
  history: browserHistory,
}); 

    <Router history={history}>
      <Route path="/" component={IndexPage} /> 
      <Route path="/test" component={Test} /> 
    </Router>

**Comment by afc163** [comment]
到人家博客报告问题？！！

**Comment by linginging** [comment]
没注意，发错地方了

**Comment by sorrycc** [comment]
重复了。
