### ISSUE TITLE
dva new 问题

### ISSUE THREAD

**Issue by kimoziiiii** [sorrycc/blog#20]
如图:
![qq 20161226181207](https://cloud.githubusercontent.com/assets/8429793/21480360/1d60a1a4-cb97-11e6-8d47-02d11b23e742.png)

**Comment by sorrycc** [comment]
npm publish 时漏文件了，试试 0.7.3 版本。

**Comment by wklc2014** [comment]
`npm install -g dva@0.7.3`
直接按钮dva只能安装0.7.1
如何安装0.7.3版本？
@sorrycc

**Comment by sorrycc** [comment]
```bash
$ npm i dva-cli -g
```

默认就是 0.7.3 了。

**Comment by kimoziiiii** [comment]
嗯 没问题了 :+1:
