### ISSUE TITLE
使用django做后端该如何与dva做数据传输？

### ISSUE THREAD

**Issue by gasxia** [sorrycc/blog#27]
可能问题并不贴合文章，也显得很是伸手党。但是这个问题我也思考和google了很久，一直没有找到答案。
所以在这里冒昧的问下。

是用django接受url访问，返回模版html，内嵌antd组件吗？

还是说完全由dva接管前段，所有数据都通过api接口从后端django获取？

对于这个问题，我一直没有理清思路，望作者指点一二，或者给我一些链接，参考书籍。
谢谢～

**Comment by iboying** [comment]
#18 ，这个例子做完你应该就明白了

**Comment by gasxia** [comment]
@iboying 👌谢谢
