### ISSUE TITLE
Uncaught SyntaxError: Unexpected token  < index.js:1,

### ISSUE THREAD

**Issue by xiak** [sorrycc/blog#28]
当我访问http://localhost:8000/api/users 时候会出现Uncaught SyntaxError: Unexpected token < index.js:1,
然后这个页面不会返回JSON数据。
PS:我单独访问http://jsonplaceholder.typicode.com/users是可以访问的

**Comment by sorrycc** [comment]
参考 https://github.com/dvajs/dva-example-user-dashboard ，对比下有啥区别。
