### ISSUE TITLE
12 步 30 分钟，完成用户管理的 CURD 应用 (react+dva+antd) 

### ISSUE THREAD

**Issue by sjcUD** [sorrycc/blog#30]
你好，到第三步时，浏览器输出 Uncaught SyntaxError: Unexpected token <index.js 1,这个咋解决？

**Comment by sjcUD** [comment]
有没有大神遇到过和我一样的情况呀？我小白一个，按照 作者步骤，到第三步就死掉了，浏览器提示Uncaught SyntaxError: Unexpected token <index.js 1,这个咋弄喔？求回复，求解决，困扰我几天了

**Comment by sjcUD** [comment]
有没有大神遇到过和我一样的情况呀？我小白一个，按照 作者步骤，到第三步就死掉了，浏览器提示Uncaught SyntaxError: Unexpected token <index.js 1,这个咋弄喔？求回复，求解决，困扰我几天了，
localhost:8000能正常访问dva,但是http://localhost:8000/api/users 浏览器就报错，代理也做了，

**Comment by sorrycc** [comment]
dva 问题请到 https://github.com/dvajs/dva/issues 提问。
