### ISSUE TITLE
编译时报栈溢出是为什么？

### ISSUE THREAD

**Issue by MuzzyXu** [sorrycc/blog#32]
按着12步的步骤来，到第3步npm start时cmd窗口抛出一个错误
![image](https://cloud.githubusercontent.com/assets/25576632/24026722/25ae7f1a-0afe-11e7-8a86-0fc9fb438adc.png)
为什么？然后antd的css样式无法加载，需要手动import

**Comment by sorrycc** [comment]
请到 [roadhog 的 issue](https://github.com/sorrycc/roadhog/issues) 里提问。
