### ISSUE TITLE
组件重复渲染，第一次获取model的数据为空，后面2次都是相同数据

### ISSUE THREAD

**Issue by zhangxiaoj** [sorrycc/blog#36]

**Comment by zhangxiaoj** [comment]
![qq 20170526105406](https://cloud.githubusercontent.com/assets/19645467/26483311/f2884e2e-421e-11e7-960d-f8bbbca75209.png)

**Comment by zhangxiaoj** [comment]
@sorrycc   帮忙看看

**Comment by sorrycc** [comment]
请到 https://github.com/dvajs/dva/issues 这里提问。
