### ISSUE TITLE
第六步显示不正常，折腾了好久

### ISSUE THREAD

**Issue by yuyc** [sorrycc/blog#39]
![image](https://user-images.githubusercontent.com/15811147/26965926-8b866b68-4d2a-11e7-97c8-9723a15990a7.png)

**Comment by afc163** [comment]
This is rude.

**Comment by caolinjian** [comment]
人家blog不要写到这里啊，，，
`{
  "entry": "src/index.js",
  "disableCSSModules": false,
  "publicPath": "/",
  "theme": {
    "@primary-color": "#1DA57A",
    "@link-color": "#1DA57A",
    "@border-radius-base": "2px",
    "@font-size-base": "16px",
    "@line-height-base": "1.2"
  },
  "autoprefixer": null,
  "proxy": {
    "/api": {
      "target": "http://jsonplaceholder.typicode.com/",
      "changeOrigin": true,
      "pathRewrite": { "^/api" : "" }
    }
  },
  "extraBabelPlugins": [
    "transform-runtime",
    ["import", { "libraryName": "antd", "style": "css" }]
  ],
  "env": {
    "development": {
      "extraBabelPlugins": [
        "dva-hmr"
      ]
    }
  }
}
`
你看看你的配置对不对，样式显示不出来显然是antd的样式没加进去

**Comment by sorrycc** [comment]
https://github.com/dvajs/dva/issues

**Comment by yuyc** [comment]
谢谢了，按照博客克隆下来的.roadhogrc文件替换成三楼给的配置就好了，看来我要好好看看roadhog的配置。
