### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by cc17** [sorrycc/blog#43]
我有个这样的场景：
list = [
  {
     infoList:[
       {
          name:'xx'
        }
     ] 
  }
];

循环list的时候，infoList里面的item动态增加了checked属性变成：
list = [
  {
     infoList:[
       {
          name:'xx',
          checked: true/false
        }
     ] 
  }
];
这个属性我是通过：
extendObservable(commodityItem,{
    checked: false
});
这种方式让其变成obserable的。现在我想在ui层面上事件修改,如：
<select checked={item.checked} onChanage={(checked)=>{  item.checked = checked;  }} />
不起作用额，想请教下应该怎么做？刚开始用mobx。感谢。

**Comment by sorrycc** [comment]
dva 问题的话请到 https://github.com/dvajs/dva/issues 提问。
