### ISSUE TITLE
运行npm start出错

### ISSUE THREAD

**Issue by willisaway** [sorrycc/blog#44]
Failed to start the server, since you have enabled dllPlugin, but have not run
roadhog buildDll` before `roadhog server`.

请问这个是什么错误

**Comment by afc163** [comment]
@sorrycc 可以把这个打开。

<img width="794" alt="image" src="https://user-images.githubusercontent.com/507615/28238329-c8374c1a-6983-11e7-8a25-45eb2d39cbec.png">
