### ISSUE TITLE
添加proxy后，路由匹配不到

### ISSUE THREAD

**Issue by wangweifeng66** [sorrycc/blog#45]
http://localhost:8000/#/api/users?_k=jdmjn2

报错：browser.js:49 Warning: [react-router] Location "/api/users" did not match any routes

**Comment by sorrycc** [comment]
dva 问题请到 https://github.com/dvajs/dva/issues 提问。

**Comment by solarhell** [comment]
@sorrycc 感觉你都可以加个issue template了。。告诉他们dva问题出门左转 不然watch了每次都被这些issue给刷屏
