### ISSUE TITLE
npm安装sass一直报错

### ISSUE THREAD

**Issue by ooolog** [sorrycc/blog#53]
通过dva 创建项目后 start能起来，然后执行 npm i node-sass --save-dve 就报错，然后再start 项目就起不来了。
![image](https://user-images.githubusercontent.com/15353314/34339798-fb23d69c-e9b3-11e7-80cf-2d8c65d5d582.png)

**Comment by ishenli** [comment]
这是人家的博客。。 dva的issue提到https://github.com/dvajs/dva/issues @ooolog
