### ISSUE TITLE
dva@2.0怎么配置本地第三方插件

### ISSUE THREAD

**Issue by weeduty** [sorrycc/blog#54]
比如：在src/assets/ab.js
ab.js为第三方本地库
开发阶段怎么配置和引用。

npm start后，查看页面localhost:8080/index.js可以访问到，直接打开index.js同级目录下面文件就访问不到了，请问是什么原因，又没有地方配置 --content base
.roadhogrc文件需要配置什么嘛

**Comment by yvanwangl** [comment]
@weeduty 这是人家的博客。。 `dva` 的 `issue` 提到https://github.com/dvajs/dva/issues
