### ISSUE TITLE
.roadhogrc 新建的工程怎么没有这个文件

### ISSUE THREAD

**Issue by ljunf888** [sorrycc/blog#59]
dva  脚手架生成的 工程没有 .roadhogrc 这个文件
而教程例子里都有

**Comment by sorrycc** [comment]
roadhog@2 是用的 .webpackrc 文件。

**Comment by ljunf888** [comment]
收到，非常感谢！

2018-02-08 


李俊峰 13311268618



发件人：chencheng (云谦) <notifications@github.com>
发送时间：2018-02-08 16:04
主题：Re: [sorrycc/blog] .roadhogrc 新建的工程怎么没有这个文件 (#59)
收件人："sorrycc/blog"<blog@noreply.github.com>
抄送："ljunf888"<bjlijunfeng@126.com>,"Author"<author@noreply.github.com>

roadhog@2 是用的 .webpackrc 文件。
