### ISSUE TITLE
如何配置hash，除了有个hash：true属性，没有其他文档了，想麻烦问下怎么配置

### ISSUE THREAD

**Issue by yiwuxing** [sorrycc/blog#77]
是这样的，我需要在index.html的文件里用script ,里面的src地址希望加上hash，
<script src="http://nodestatic.fbstatic.cn/weblts_spa_online/fenbicampusoffergame/index.js"></script>
在这个src后加个hash，请问怎么实现

**Comment by sorrycc** [comment]
不要在这里提问。

**Comment by yiwuxing** [comment]
请问在哪提问呢

**Comment by sorrycc** [comment]
@yiwuxing 

## umi 问题

### issue

> 提 issue 请带上可复现步骤或仓库，否则会被关闭。

https://github.com/umijs/umi/issues/new

### 微信群

加 `sorryccpro` 注明 `umi`。

### 钉钉群

<img src="https://gw.alipayobjects.com/zos/rmsportal/jPXcQOlGLnylGMfrKdBz.jpg" width="40" />

## dva 问题

> 提 issue 请带上可复现步骤或仓库，否则会被关闭。

### issue

https://github.com/dvajs/dva/issues/new

### 微信群

加 `sorryccpro` 注明 `dva`。

## roadhog 问题

### issue

https://github.com/sorrycc/roadhog/issues/new

## antd 问题

本人不维护 antd，请加官方钉钉群咨询，群号 `11722346`。

## 其他问题

https://github.com/sorrycc/ama/issues/new
