### ISSUE TITLE
请问下umi中COMPRESS不是批处理文件，这个需要怎么解决

### ISSUE THREAD

**Issue by xiao-qi-l** [sorrycc/blog#98]
在umi中执行打包命令的时候，如下所示：“build”: "COMPRESS=none umi build",会抛出来一个COMPRESS不是批处理文件的错误，难道跟使用的系统环境有关系吗，我的是window系统

**Comment by xiao-qi-l** [comment]
抱歉，提交错误

**Comment by justjavac** [comment]
使用 cross-env
